"""rename content to data in conversations

Revision ID: 2eb276c7ae2c
Revises: 
Create Date: 2025-12-16 21:17:50.519175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb276c7ae2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Conversation_id'), table_name='Conversation')
    op.drop_index(op.f('ix_Conversation_token'), table_name='Conversation')
    op.drop_table('Conversation')
    op.add_column('conversations', sa.Column('data', sa.String(), nullable=True))
    op.drop_column('conversations', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('content', sa.VARCHAR(), nullable=True))
    op.drop_column('conversations', 'data')
    op.create_table('Conversation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Conversation_token'), 'Conversation', ['token'], unique=1)
    op.create_index(op.f('ix_Conversation_id'), 'Conversation', ['id'], unique=False)
    # ### end Alembic commands ###
